name: Run all test cases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make all
      run: make all
    - name: Run tests
      run: ./run_tests.sh
